Algoritmo "Leonardo Russo"
//  
//  
//
//
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Tung
// Descrição   : Circuferencia
// Autor(a)    : Leonardo Russo
// Data atual  : 12/03/2026
// Seção de Declarações das variáveis 
RAIO: REAL
PERIMETRO: REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Pi<-3,1416

ESCREVAL("DIGITE O VALOR DO RAIO")
LEIA(RAIO)
PERIMETRO<-(2*Pi*RAIO)

ESCREVAL("PERIMETRO=",PERIMETRO)


Fimalgoritmo