Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2026
Var
// Seção de Declarações das variáveis 
RAIO: REAL
PERIMETRO: REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Pi<-3,1416

ESCREVAL("DIGITE O VALOR DO RAIO")
LEIA(RAIO)
PERIMETRO<-(2*Pi*RAIO)

ESCREVAL("PERIMETRO=",PERIMETRO)


Fimalgoritmo