Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2026
Var
// Seção de Declarações das variáveis 
CELSIUS: REAL
FARENHEIT: REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


ESCREVAL("DIGITE O VALOR DA TEMPERATURA CELSIUS")
LEIA(CELSIUS)
FARENHEIT<-(9/5*CELSIUS+32)

ESCREVAL("TEMPERATURA=",FARENHEIT, " [F]")


Fimalgoritmo