Algoritmo "Leonardo Russo"
//
//
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Tung
// Descrição   : Farenheit
// Autor(a)    : Leonardo Russo
// Data atual  : 12/03/2026
Var
// Seção de Declarações das variáveis 
CELSIUS: REAL
FARENHEIT: REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


ESCREVAL("DIGITE O VALOR DA TEMPERATURA CELSIUS")
LEIA(CELSIUS)
FARENHEIT<-(9/5*CELSIUS+32)

ESCREVAL("TEMPERATURA=",FARENHEIT, " [F]")


Fimalgoritmo