Algoritmo "Leonardo Russo"
// Descrição   : Exercício 4 - Manipulação de variáveis.
//               O algoritmo atribui valores às variáveis A, B e C,
//               realiza algumas alterações nesses valores e ao final
//               exibe o conteúdo final de cada variável.
// Autor(a)    : Leonardo Russo
// Data atual  : 12/03/2026

Var
// Seção de Declarações das variáveis
a, b, c: inteiro

Inicio
// Seção de Comandos

 a <- 8
 b <- 5
 c <- a + b
 b <- 15
 a <- 5
 b <- b - 2

 escreva("|A:",a,"|B:",b,"|C:",c,"|")

Fimalgoritmo