Algoritmo "Exercicio - 6"
// Descrição   : Calcula o valor de duas expressões matemáticas.
// Autor(a)    : Leonardo Russo
// Data atual  : 12/03/2026

Var
resultado1, resultado2: inteiro

Inicio

resultado1 <- ((4 * 8) + 3) * 7
resultado2 <- ((12 - 5) * (-4)) + (3 * (-2))

escreval("Resultado da primeira expressão: ", resultado1)
escreval("Resultado da segunda expressão: ", resultado2)

Fimalgoritmo