Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/04/2026
Var
// Seção de Declarações das variáveis 
numero, contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Digite a tabuada que gostaria de saber: ")
leia(numero)

para contador de 1 ate 10 faca
escreval(numero, " x",contador, " =", numero * contador)
fimpara
Fimalgoritmo